{{- if .Values.analytics.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: analytics-secret
  labels:
    {{- include "protopie.labels" . | nindent 4 }}
type: Opaque
data:
  ae-api-user-pass: {{ include "protopie.analytics.aeApiUserPass" . | b64enc | quote }}
  django-secret-key: {{ include "protopie.analytics.djangoSecretKey" . | b64enc | quote }}
{{- end }}
