{{- if and .Values.userTesting.enabled (not .Values.userTesting.useLegacy) }}
apiVersion: v1
kind: Secret
metadata:
  name: user-testing-db-secret
  labels:
    {{- include "protopie.labels" . | nindent 4 }}
    app: user-testing-db
type: Opaque
data:
  password: {{ .Values.userTesting.db.password | b64enc | quote }}
  postgres-password: {{ .Values.userTesting.db.postgresPassword | b64enc | quote }}
{{- end }}
