{{- if and .Values.userTesting.enabled (not .Values.userTesting.useLegacy) }}
apiVersion: v1
kind: Secret
metadata:
  name: user-testing-app-secret
  labels:
    {{- include "protopie.labels" . | nindent 4 }}
    app: user-testing-server
type: Opaque
data:
  jwt-secret: {{ .Values.userTesting.jwtSecret | b64enc | quote }}
  cloud-api-service-key: {{ .Values.userTesting.cloudApiServiceKey | b64enc | quote }}
{{- end }}
