{{- if and .Values.userTesting.enabled (not .Values.userTesting.useLegacy) }}
apiVersion: v1
kind: Service
metadata:
  name: user-testing-server
  labels:
    {{- include "protopie.labels" . | nindent 4 }}
    app: user-testing-server
spec:
  type: ClusterIP
  ports:
    - port: 3030
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: user-testing-server
{{- end }}
